version : '3'

services:
    lb:
        image: haproxy:1.8.30
        ports:
            - "8080:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy:ro
    ws1:
        image: chatapp
        environment:
            - APPID=1111
    ws2:
        image: chatapp
        environment:
            - APPID=2222
    ws3:
        image: chatapp
        environment:
            - APPID=3333
    ws4:
        image: chatapp
        environment:
            - APPID=4444
            
    ws5:
        image: chatapp
        environment:
            - APPID=5555
            
    ws6:
        image: chatapp
        environment:
            - APPID=6666
    rds:
        image: redis